codecov:
  allow_coverage_offsets: True
coverage:
  status:
    project: off
    patch: off
comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
