- name: "A-Element-R"
  description: "Issues affecting the port of Element's crypto layer to Rust"
  color: "bfd4f2"
- name: "A-Packaging"
  description: "Packaging, signing, releasing"
  color: "bfd4f2"
- name: "A-Technical-Debt"
  color: "bfd4f2"
- name: "A-Testing"
  description: "Testing, code coverage, etc."
  color: "bfd4f2"
- name: "backport staging"
  description: "Label to automatically backport PR to staging branch"
  color: "B60205"
- name: "Dependencies"
  description: "Pull requests that update a dependency file"
  color: "0366d6"
- name: "Easy"
  color: "5dc9f7"
- name: "Sponsored"
  color: "ffc8f4"
- name: "T-Deprecation"
  description: "A pull request that makes something deprecated"
  color: "98e6ae"
- name: "T-Other"
  description: "Questions, user support, anything else"
  color: "98e6ae"
- name: "X-Blocked"
  color: "ff7979"
- name: "X-Breaking-Change"
  color: "ff7979"
- name: "X-Reverted"
  description: "PR has been reverted"
  color: "F68AA3"
- name: "X-Upcoming-Release-Blocker"
  description: "This does not affect the current release cycle but will affect the next one"
  color: "e99695"
- name: "Z-Community-PR"
  description: "Issue is solved by a community member's PR"
  color: "ededed"
- name: "Z-Flaky-Test"
  description: "A test is raising false alarms"
  color: "ededed"
