peerDependencyRules:
    allowedVersions:
        eslint: "8"

allowedDeprecatedVersions:
    eslint: "8"

overrides:
    expect: 30.4.1

allowBuilds:
    unrs-resolver: false

minimumReleaseAgeExclude:
    # Bypassing for this version, obviously this is only necessary
    # temporarily so if you're reading this, you can almost certainly
    # remove it
    - "@matrix-org/*"
