allowBuilds:
    esbuild: false
    unrs-resolver: false

allowedDeprecatedVersions:
    eslint: "8"

minimumReleaseAgeExclude:
    - "@matrix-org/*"

overrides:
    expect: 30.4.1
    vite: 8.1.5

peerDependencyRules:
    allowedVersions:
        eslint: "8"
