name: Build downstream artifacts
on:
    merge_group:
        types: [checks_requested]

    pull_request: {}

    # For now at least, we don't run this or the downstream-end-to-end-tests against pushes
    # to develop or master.
    #
    #push:
    #    branches: [develop, master]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build-element-web:
        name: Build element-web
        uses: matrix-org/matrix-react-sdk/.github/workflows/element-web.yaml@v3.96.1
        with:
            matrix-js-sdk-sha: ${{ github.sha }}
            react-sdk-repository: matrix-org/matrix-react-sdk
