name: Build downstream artifacts
on:
    pull_request: {}
    merge_group:
        types: [checks_requested]

    # For now at least, we don't run this or the cypress-tests against pushes
    # to develop or master.
    #
    # Note that if we later choose to do so, we'll need to find a way to stop
    # the results in Cypress Cloud from clobbering those from the 'develop'
    # branch of matrix-react-sdk.
    #
    #push:
    #    branches: [develop, master]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build-element-web:
        name: Build element-web
        uses: matrix-org/matrix-react-sdk/.github/workflows/element-web.yaml@develop
        with:
            matrix-js-sdk-sha: ${{ github.sha }}
            react-sdk-repository: matrix-org/matrix-react-sdk
