name: Build downstream artifacts
on:
    pull_request: {}
    merge_group:
        types: [checks_requested]
    push:
        branches: [develop, master]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build-element-web:
        name: Build element-web
        uses: matrix-org/matrix-react-sdk/.github/workflows/element-web.yaml@HEAD
        with:
            matrix-js-sdk-sha: ${{ github.sha }}
            react-sdk-repository: matrix-org/matrix-react-sdk
