# Gitflow merge-back master->develop
name: Merge master -> develop
on:
    push:
        branches: [master]
    workflow_call:
        secrets:
            ELEMENT_BOT_TOKEN:
                required: true
        inputs:
            dependencies:
                description: List of dependencies to reset.
                type: string
                required: false
            dir:
                description: The directory to release
                type: string
                default: "."
concurrency: ${{ github.workflow }}
permissions: {} # Uses ELEMENT_BOT_TOKEN
jobs:
    merge:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
              with:
                  # We will be pushing to this branch and want the CI to run after we do so we cannot use the GITHUB_TOKEN
                  token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  fetch-depth: 0
                  persist-credentials: true

            - name: Get actions scripts
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
              with:
                  repository: matrix-org/matrix-js-sdk
                  persist-credentials: false
                  path: .action-repo
                  sparse-checkout: |
                      scripts/release

            - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  cache: "pnpm"
                  node-version-file: package.json

            - name: Install Deps
              run: "pnpm install --frozen-lockfile --ignore-scripts"

            - name: Set up git
              run: |
                  git config --global user.email "releases@riot.im"
                  git config --global user.name "RiotRobot"

            - name: Merge to develop
              run: .action-repo/scripts/release/merge-master-to-develop.sh

            - name: Reset dependencies
              if: inputs.dependencies
              working-directory: ${{ inputs.dir }}
              run: |
                  while IFS= read -r PACKAGE; do
                      [ -z "$PACKAGE" ] && continue

                      CURRENT_VERSION=$(cat package.json | jq -r .dependencies[\"$PACKAGE\"])
                      echo "Current $PACKAGE version is $CURRENT_VERSION"

                      if [[ "$CURRENT_VERSION" == "null" ]]
                      then
                          echo "Unable to find $PACKAGE in package.json"
                          exit 1
                      fi

                      if [[ "$CURRENT_VERSION" == *"#develop" ]]
                      then
                          echo "Not updating dependency $PACKAGE"
                          continue
                      fi

                      echo "Resetting $PACKAGE to develop branch..."
                      pnpm add "github:matrix-org/$PACKAGE#develop"
                      git add -u
                      git commit -m "Reset $PACKAGE back to develop branch"
                  done <<< "$DEPENDENCIES"
              env:
                  DEPENDENCIES: ${{ inputs.dependencies }}

            - name: Push changes
              run: git push origin develop
