# Gitflow merge-back master->develop
name: Merge master -> develop
on:
    push:
        branches: [master]
concurrency: ${{ github.workflow }}
jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  fetch-depth: 0

            - name: Get actions scripts
              uses: actions/checkout@v4
              with:
                  repository: matrix-org/matrix-js-sdk
                  persist-credentials: false
                  path: ../action-repo
                  sparse-checkout: |
                      scripts/release

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Set up git
              run: |
                  git config --global user.email "releases@riot.im"
                  git config --global user.name "RiotRobot"

            - name: Merge to develop
              run: |
                  git checkout develop
                  git merge -X ours master

            - name: Run post-merge-master script to revert package.json fields
              run: ../action-repo/scripts/release/post-merge-master.sh
