# Gitflow merge-back master->develop
name: Merge master -> develop
on:
    push:
        branches: [master]
concurrency: ${{ github.workflow }}
jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.ELEMENT_BOT_TOKEN }}
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Set up git
              run: |
                  git config --global user.email "releases@riot.im"
                  git config --global user.name "RiotRobot"

            - name: Merge to develop
              run: |
                  git checkout develop
                  git merge -X ours master

            - name: Update package.json fields
              run: |
                  # When merging to develop, we need revert the `main` and `typings` fields if we adjusted them previously.
                  for i in main typings browser
                  do
                      # If a `lib` prefixed value is present, it means we adjusted the field
                      # earlier at publish time, so we should revert it now.
                      if [ "$(jq -r ".matrix_lib_$i" package.json)" != "null" ]; then
                          # If there's a `src` prefixed value, use that, otherwise delete.
                          # This is used to delete the `typings` field and reset `main` back to the TypeScript source.
                          src_value=$(jq -r ".matrix_src_$i" package.json)
                          if [ "$src_value" != "null" ]; then
                              jq ".$i = .matrix_src_$i" package.json > package.json.new && mv package.json.new package.json && yarn prettier --write package.json
                          else
                              jq "del(.$i)" package.json > package.json.new && mv package.json.new package.json && yarn prettier --write package.json
                          fi
                      fi
                  done

            - name: Commit and push changes
              run: |
                  git add package.json
                  git commit -m "Resetting package fields for development"
                  git push origin develop
