name: Publish to npm
on:
    workflow_call:
        inputs:
            dir:
                description: The directory to release
                type: string
                default: "."
        outputs:
            id:
                description: "The npm package@version string we published"
                value: ${{ jobs.npm.outputs.id }}
permissions: {}
jobs:
    npm:
        name: Publish to npm
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            id-token: write
        outputs:
            id: ${{ steps.npm-publish.outputs.id }}
        steps:
            - name: 🧮 Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  ref: staging
                  persist-credentials: false

            - name: 🔨 Setup pnpm & node
              uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
              with:
                  runtime: node
                  cache: true
                  install: true

            - name: 🚀 Publish to npm
              id: npm-publish
              working-directory: ${{ inputs.dir }}
              run: |
                  version=$(jq -r '.version' package.json)
                  if [[ "$version" == *-rc.* ]]; then
                      tag=next
                  else
                      tag=latest
                  fi

                  pnpm publish --provenance --access public --publish-branch staging --tag "$tag"
                  release=$(jq -r '"\(.name)@\(.version)"' package.json)
                  echo "id=$release" >> $GITHUB_OUTPUT
