name: Move labelled issues to correct projects

on:
    issues:
        types: [labeled]
permissions: {} # We use ELEMENT_BOT_TOKEN instead
jobs:
    call-triage-labelled:
        uses: element-hq/element-web/.github/workflows/triage-labelled.yml@6339bcda15c71d209303b18a06a9b1c021220bf9
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
