name: Move labelled issues to correct projects

on:
    issues:
        types: [labeled]

jobs:
    call-triage-labelled:
        uses: vector-im/element-web/.github/workflows/triage-labelled.yml@develop
        secrets: inherit
